name: logging_service
description: "A new Flutter project."
version: 0.0.3

environment:

  sdk: ^3.5.2
  flutter: '>=3.3.0'



dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^7.0.0
  json_view: ^0.4.2
  dio: ^5.9.0
  intl: ^0.20.2
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1
  plugin_platform_interface: ^2.1.8
  shake_flutter: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.aghyv.samir.logging_service
        pluginClass: LoggingServicePlugin
      ios:
        pluginClass: LoggingServicePlugin
      linux:
        pluginClass: LoggingServicePlugin
      macos:
        pluginClass: LoggingServicePlugin
      windows:
        pluginClass: LoggingServicePluginCApi
      web:
        pluginClass: LoggingServiceWeb
        fileName: logging_service_web.dart


